name: Golang Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  test-go:
    runs-on: ubuntu-latest
    name: Test Go (${{ matrix.go }})
    strategy:
      matrix:
        go: ["1.12", "1.13", "1.14", "1.15"]
    steps:
      - uses: actions/checkout@v2
      - name: Set Up golang-${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: |
          go mod download
          go mod vendor
          go mod verify
      - name: Test
        run: |
          go test -race -v ./...
